development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Azimuth
  admin_email: ychaker@o19s.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://li47-74.members.linode.com/
  site_name: Bort
  admin_email: ychaker@o19s.com
  
production:
  site_url: http://li47-74.members.linode.com/
  site_name: Azimuth
  admin_email: ychaker@o19s.com
